name: Install dependencies
runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      id: yarn-cache
      if: env.YARN_ENABLE_IMMUTABLE_INSTALLS != true
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-nm-${{ hashFiles('yarn.lock', 'package.json', '*/*/package.json') }}
        restore-keys: ${{ runner.os }}-nm-

    - name: Install project dependencies
      shell: bash
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn
      env:
        YARN_ENABLE_IMMUTABLE_INSTALLS: ${{ startsWith(github.head_ref, 'renovate/') != true }}
