name: pr

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  yarn-install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      # cancel any previous workflow runs in progress (PR only)
      - name: Cancel Previous Runs
        if: ${{ github.event_name == 'pull_request' }}
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/yarn-install

